server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dzuoj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
alipay:
  app-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHgSC2VuXPYbOn6DUVADLBm6u/bGIhbd+uUj45lYucgEbE0Nj5kzOFQsXZh4tXBqdcRjR6J8v2DwC6zAhjfPWwbpcS0GdKhxRLLrJmrCF8Gt+O59N8TMB2+sBc2JpEER1kfQ9YUswGJ53ICwzIzP02CZU4TLJ/qmqURNwS6Lng4kyV/j+mBRRuNzssRksocfuELhQMpWmbf+GQo417Hj0fW7sPP+KBgtOCUNdA8JN6158lK6uotHwIgwr/KC/lyZbnO4vBxJg2WfBxsY1nB+gEMfEMKDVJWgPi6K1/vYaarRhVdyMZin0rbjDPqPpboZU3ieI+6UEhRYae7UM9FDwvAgMBAAECggEBALT72m4vxMjuLCnNSKJljKYAj7zXGOqUn0+nwlVA6ecuo4SWpc87D4j7uzqMcQagvaDC+4Y5phjxIUtUHuQKD2Rf3uMtdhaxFeLiWOs1iiboxhgBDOT9R7hn36wav0+yawSnQw1wBzAqLkO0aoObGrYz2U+6nE+ejJM3KKJqx31Ok99hht3qxaa259fY7HqCxj76IVC2Bpv0gOKaJoz8IKz6IVYxRuGgLRZops1ph2bvYA3PB0Hx7G0E7isKWnzezkeTdvzsAYpjFexWIDH8VerWaBlBL6n3sKm84wMEegmf5sKQQW8c24qODcawtM22XgUfPo3Zo8LjgB7UAbyGCXECgYEA52mhyc3ycSriCcpQiNRhLHNG3i6+UmrQpB+WcBUR899jkulXAhD691Nef1Mofr9cbcsKJn+LUg9dm1IpkWG5gCKnttTaDJShQcsjGFigFJkQ262Y3FsytM/yWuUFe/b/yA9YwkJk9K0rrcMLd7hbAmTX5b+vDiDcKmaz9nlq9zcCgYEA3LOZkInxgoTI4uZRAkCSWE9MdWfat+IKag8iaC7syi6BYGmExJxeeiOqkBYeNpD4RXFVz51Wji5PVzWqqPlXjKQPbBVMEpT6PRJMjp/V96tWdtpEk0z7OfgKCUiV7O2ViNw+nMgVT1j3zGXABkJpyMHEfYGdxWNFJbsnSSdV7skCgYBrFPAup8QGJefOy/WUO2Jz5Svn6A1dqdu99nfwiW9zP+2dr6f5Zs4a4FMb6+kTLY2hqJCb2+0mHcIc+1oM0gG6j064RapYo/YyscMdovUAUwv/+0Z+wRynmon1EYEGKfeWJbPWwE5jAjbyAw0tavuCEhPtVlO03/PBEyE3blvW5QKBgQC3mdGOpLL9WWmlGOUbcoxMWuvIX/VcM/dl8+EzupXSPI30ntOMnGkcQr+JzlykGEXxvy8b4FA5R91JN6QZnhRvM6yAxdbbPoROegKmQ+HEgA0WIs4ZnFkDCI2Q24md6KgViuOrmefgcqryp1Lv4iAOmuPTZRjTNJo5oVA1UzvxwQKBgG+UIvPZGrHF+C6VMJTjQFXeXfSieZexSw+VnVQ1QqbyW5D5COEVU4SrZDXRey1sg6kKOjpzpDm2KF1gQCmbVA1D5euqM7PmHyGEzQMRsCWnp8Q70WxhsqbI2u/Tb1X1qmh5dz53qa9/d0en1sEV3cQBIAGcDkrLThIQppZEC5A0
  notify-url: http://8hny4f.natappfree.cc/alipay/notify
  app-id: 2016101500690610
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjMn+O9VbsSty9FIBYQqFnl8b4uWQwCVMs77uFBvSJ7AEu2xLow1QI1eoxGTPNC+rHG55SSyYnLPeWbV7VEvhUkI8QiMfPNRVQr4dbBRuGdI3xIAX68nu49KJ73sWF1/TYspr9Fx1/Gz3l/o3jvcnfmQzGGyFdJoVLufsTowBNlo7MdajMhHJjluDCoNCCHQAvRPe4E7KY1XN8WHVj5w1MYD1BlHv+IocQ64NUix/fIA29HHCt8tXwnh0Egisjhu7RebWECUIsHzu4203n/JX8A7i5tyuiPjY+Qfx+sIdtUCyYfrZniAravPLA5py/1Mp8ypYmuOSc35oJx6t+UqoGQIDAQAB

